### ISSUE TITLE
Ese Jose nomas arruino el acomodo

### ISSUE THREAD

**Issue by AngelILee** [Xotl/Smash-League#43]
Tabla de esta semana:

# | Player | Score
-- | -- | --
1 | Neku | 18
2 | César Gutman | 18
3 | Xotl, José "El Iceberg" Rosales | 17
4 | Angel Lee, El Minion | 15
5 | Sammy | 9
6 | Fer Señior | 7
7 | D.I.O. | 6
8 | David | 5
9 | Alan, El Chino | 3
10 | Gilberto "Gil" Ruelas | 2

Como debe quedar:

# | Player | Score
-- | -- | --
1 | Neku | 19----------------------------------------------Se incrementa un punto por que perdi mi moneda con el.

2 | César Gutman | 18
3 | Angel Lee ,Xotl, José "El Iceberg" Rosales | 17---------Quedo con 17 puntos arriba de Jose y de Xotl por que les gane a ellos 2 esta semana

4 | El Minion | 15
5 | Sammy | 9
6 | Fer Señior | 7
7 | D.I.O. | 6
8 | David | 5
9 | Alan, El Chino | 3
10 | Gilberto "Gil" Ruelas | 2

**Comment by Xotl** [comment]
Fixed in commits [44f1816](https://github.com/Xotl/Smash-League/commit/44f18162c9bd07e551cdce9878326cd22bddcf62) & [56c8a7d](https://github.com/Xotl/Smash-League/commit/56c8a7d3a57219b2185757e0b6a5f446a07f116a)

**Comment by Xotl** [comment]
Now fixed all in commit [
6b32c69](https://github.com/Xotl/Smash-League/commit/6b32c693452c3c0fd6a8ef5778f3eb38e645f0c0)

**Comment by Xotl** [comment]
Now should be all correct
