### ISSUE TITLE
0 coins on 0 loses

### ISSUE THREAD

**Issue by Jarv1193** [Xotl/Smash-League#69]
## Expected Behavior
If I don't lose anytime I should have my coins

## Actual Behavior
I lose my coins and I didn't lose a match so I'm unable to continue challenging people

## Steps to Reproduce the Problem

  1.  Be on 6th place
  2. Challenge people
  3. Don't lose

## Screenshot
![image](https://user-images.githubusercontent.com/37460773/67969332-b0d38e00-fbce-11e9-899c-50c2e2a4282f.png)

## Specifications

  - Version: Smash League 3.0.1
  - Platform:

**Comment by Xotl** [comment]
Fix merged
